crm_tools_homepage:
    path:     /
    defaults: { _controller: CRMToolsBundle:Default:index }

crm_tools_graph:
    path:     /graphs_performance
    defaults: { _controller: CRMToolsBundle:Monitoring:graph }

crm_tools_creat:
    path:     /creat
    defaults: { _controller: CRMToolsBundle:Default:creat }

crm_tools_display:
    path:     /display
    defaults: { _controller: CRMToolsBundle:Default:display }

crm_logs_view:
    path:     /logs_view
    defaults: { _controller: CRMToolsBundle:Monitoring:contact }

crm_errors_analysis:
    path:     /analyse_erreurs
    defaults: { _controller: CRMToolsBundle:DataQuality:errorsAnalysis}



