crm_tools_homepage:
    path:     /
    defaults: { _controller: CRMToolsBundle:Default:index }

crm_tools_creat:
    path:     /creat
    defaults: { _controller: CRMToolsBundle:Default:creat }

crm_tools_display:
    path:     /display
    defaults: { _controller: CRMToolsBundle:Default:display }

