<?php

namespace CRM\ToolsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GraphNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GraphNameRepository extends EntityRepository
{
    public function  recupeWithWhere(){

        $qb = $this->createQueryBuilder('g')
            ->select ('g.id, g.name, g.averageDurationJob')
            ->where('g.enableDisplay = true')
            ->andWhere('g.id = 1')
            ->getQuery();

        

        return $graphs=$qb->getResult();
    }
}
